# Generated by Django 5.2.14 on 2026-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_seed_dynamic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='secondary_image',
            field=models.ImageField(blank=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='home_hero_image',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='operating_image',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
    ]
